//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleEntry
    {
        public int RoleEntriesId { get; set; }
        public int ArtistId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Role Role { get; set; }
    }
}
